### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function in Firefox with Browserify/Webpack

### ISSUE THREAD

**Issue by Heath123** [ProtoDef-io/node-protodef#100]
`.captureStackTrace` is an undocumented V8 function that won't work on other JavaScript engines, which breaks Browserify/Webpack in Firefox (although it works in Chrome). On Edge the error is `Object doesn't support property or method 'captureStackTrace'`.

This happens here:
```js
class ExtendableError extends Error {
  constructor (message) {
    super(message)
    this.name = this.constructor.name
    this.message = message
    Error.captureStackTrace(this, this.constructor.name)
  }
}
```

**Comment by roblabla** [comment]
it should be enough to call this function only if it exists, e.g.

```js
if (Error.captureStackTrace != null)
    Error.captureStackTrace(this, this.constructor.name)
```

On Firefox (and most other browser), the `stack` property of Error seems to be created on Error construction and not need to be manually acquired.
