### ISSUE TITLE
Setup PAT token

### ISSUE THREAD

**Issue by rom1504** [ProtoDef-io/node-protodef#161]
Can't figure out how to create one

Do you know @extremeheat ?

**Comment by extremeheat** [comment]
Setting the token to built in secrets.GITHUB_TOKEN will work without a PAT but CI just won't run on the release PR. 

For creating PAT it's under Settings -> Developer settings-> Personal access tokens -> Tokens (classic). Then that token can be used for all repos the current account has access to if the "repo" permission is granted for the token
