### ISSUE TITLE
Add an option to the parser to disable partial packets

### ISSUE THREAD

**Issue by rom1504** [ProtoDef-io/node-protodef#57]
Useful for protocol that have length prefixed packets.
The benefit of disabling it is mainly to produce an error if the amount of bytes read is different from the size of the buffer.

**Comment by rom1504** [comment]
An option or a separate Parser, depending what's easier to implement.

**Comment by roblabla** [comment]
I wonder if a user-defined datatype would do the trick ?

```
{
  type: "fixed",
  typeArgs: {
    size: "selector",
    contents: dataType
  }
}
```

(A note on selector : that's #35)

**Comment by rom1504** [comment]
Well it's more of a Parser stream thing. It's kind of meta, like https://github.com/PrismarineJS/minecraft-data/issues/115

We don't store the length prefixed packet info thing in the .json (yet ?)

**Comment by rom1504** [comment]
(will avoid error like `Error: Deserialization error for play.toClient : Read error for name : 3365 is not in the mappings value` in nmp when the protocol is wrong, it will instead say something about the length of the packet)

**Comment by rom1504** [comment]
Ah I see your point. Indeed something like that would work, but only if we handle the whole packet within protodef.

That might be possible but it requires us to handle both compression and framing within protodef. But compression is async so we can't quite do that with the current interface ( #49 )

Something in between might be to make the framer and compression streams keep the length so the parser could use it.

**Comment by rom1504** [comment]
Ah actually I think it might be possible to do that by passing the size of this.queue (it shouldn't contain too much stuff since we will error out and empty it in case of pb) as a typeArgs when reading a packet in the serializer https://github.com/roblabla/ProtoDef/blob/master/src/serializer.js#L44

**Comment by rom1504** [comment]
First thing to do : create an example test case (in examples/) that requires this "fixed" to error out on the right packet.

**Comment by roblabla** [comment]
OK, so concerning this. We don't need ProtoDef to actually handle those. We just need a way to pass variables to ProtoDef. This facility actually already exists with the rootNode : just pass some data there, and it will be accessible.

I guess you'll need something more powerful than the standard "Serializer" though, as Serializer doesn't have any way to pass data like that.

**Comment by rom1504** [comment]
it's totally possible to pass the size of the chunk as a typeArgs when reading a packet. But that assumes the chunks are already split which bring us back to https://github.com/roblabla/ProtoDef/pull/60#issuecomment-190448251

(this issue only concern the Parser, not the Serializer)

**Comment by rom1504** [comment]
the "fixed" type would indeed make sense. We have something similar in raknet and it would help.

**Comment by rom1504** [comment]
this is important. Because of this we have this kind https://github.com/PrismarineJS/node-minecraft-protocol/issues/522 of silly errors.

I think we should just provide a second parser for now.

**Comment by Saiv46** [comment]
Don't we have `Parser` and `FullPacketParser` already? Also, that's not a ProtoDef should care of.

**Comment by rom1504** [comment]
Yeah this is fixed, and definitely what protodef takes care of
