### ISSUE TITLE
Make protodef-spec repo

### ISSUE THREAD

**Issue by rom1504** [ProtoDef-io/node-protodef#67]
It will contain information about what protodef is and how to implement it
* [x] datatype documentation
* [x] json test data
* [x] example of json types in the readme
* [x] wrapper list in the readme

**Comment by rom1504** [comment]
Let's call the spec repo just ProtoDef. And then it would make sense to name the repo node-protodef, @roblabla what do you think about renaming it ? (just the repo, not the package)
It makes more sense now that there is a elixir protodef (https://github.com/McEx/ProtoDef)

**Comment by hansihe** [comment]
If we decide on a naming scheme, I will rename the Elixir one so that it matches.

**Comment by rom1504** [comment]
done at https://github.com/rom1504/ProtoDef

only thing remaining here is renaming this repo to node-protodef. (Also idk if it makes sense to keep these in rom1504/ and/or roblabla/ ?)

**Comment by roblabla** [comment]
I'm all for moving ProtoDef related stuff to an Org if we start having some impl in multiple languages. @rom1504 if you want to create a `ProtoDef` org, l'll transfer this repo to it. Then we can have all the protodef related stuff in a single place ?

**Comment by rom1504** [comment]
Bah https://github.com/ProtoDef

**Comment by roblabla** [comment]
Dang.

We could get https://github.com/ProtoDef.io . It fits well too :D

**Comment by roblabla** [comment]
(Besides I could do a quick landgrab and get the associated domains, so we put the spec there :D)

**Comment by rom1504** [comment]
> Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen

**Comment by rom1504** [comment]
There's always "ProtoDefOrg". Any better idea ?

**Comment by roblabla** [comment]
That's ok. ProtoDef-io will be the link, but the name can contain dots. (You can change the name in the settings after creating the org)

**Comment by roblabla** [comment]
https://github.com/ProtoDef-io like that ? What do you think ?

**Comment by rom1504** [comment]
Yeah that works.

**Comment by roblabla** [comment]
Done. You're admin, and repo is transferred.

**Comment by rom1504** [comment]
Alright, all moved to https://github.com/ProtoDef-io.
I think the naming scheme should be X-protodef with X being something referring to the language.

Now "McEx/ProtoDef" can stay in McEx or move to ProtoDef-io, as you prefer @hansihe

**Comment by hansihe** [comment]
If you add me to the org, I'll transfer it over.

**Comment by rom1504** [comment]
Invited you.

**Comment by hansihe** [comment]
All done.
