### ISSUE TITLE
Add LICENSE to source tree

### ISSUE THREAD

**Issue by mhsjlw** [ProtoDef-io/node-protodef#85]
It is specified as MIT here: https://github.com/ProtoDef-io/node-protodef/blob/master/package.json#L13, however there is no LICENSE file in this project.

**Comment by roblabla** [comment]
This project was born from NMP code, which is BSD-3-Clause licensed.

I'm personally against GPL/LGPL and other copyleft licenses for node-protodef. MIT/ISC/Apache are fine.

**Comment by rom1504** [comment]
Why do we need a LICENSE file ?
I think it pollutes the repo .

**Comment by mhsjlw** [comment]
With no LICENSE file then GitHub can't show the repo's license status. Plus, part of the MIT license is _distributing the license with the source tree_!

**Comment by SuperOP535** [comment]
+1, having a license file makes it easier for people to see what's allowed and what's not because github parses it and shows an easy-to-read list.

**Comment by rom1504** [comment]
done
