### ISSUE TITLE
implement "split" array

### ISSUE THREAD

**Issue by louis030195** [ProtoDef-io/node-protodef#99]
It is not so clear how to do it,
for example i have a packet format:

[ID_PACKET(2 bytes)][PARAM1][SEPARATOR(for example ";" or 0x12 ...)][PARAM2][same separator]PARAM3][same separator] ...

or like you would do in most languages:

```js
console.log("aaa;bbb;ccc".split(";"))
```
>["aaa","bbb","ccc"]

is it like that ?

```json
{
  "title": "split",
  "type": "array",
  "items": [
    { "enum": ["split"] },
    {
      "type": "object",
      "properties": {
        "type": {"$ref": "dataType"},
        "separator":{"$ref": "definitions#/definitions/dataTypeArgsCount"}
      },
      "required": ["type", "separator"],
      "additionalProperties": false
    }
  ]
}
```

Also I should implement something in JS with it ?
Then I guess I have to use addType() ?

**Comment by rom1504** [comment]
Yes you have to implement it in js.
Do you have an example of such packet ?
It seems very weird to split on 0x12 if it's not a text protocol (what
happens if you have 0x12 as a int value ?)

**Comment by louis030195** [comment]
lets forget 0x12, just for ";" or "," ...
something that could be used like that

https://gist.github.com/louis030195/3398dbf7ea91ea9daa4fe38d2ce6cb51

**Comment by rom1504** [comment]
What happens in that case when the hex code for ";" is part of one of these
int32 ?

**Comment by louis030195** [comment]
Not possible ?
This kind of packet:

>GCK|1As0,0,110|0|0|0|0~0,0,1,0,0,0|50,50|10000,10000|0|120|6,0,0,0,6|3,0,0,0,3|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|1,0,0,0,1|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|

**Comment by rom1504** [comment]
What is not possible ? If you have the number 124 then you will split on
this. (124 is the char representation of '|')

These packets in your example are strings packets, not binary packets.
So just parse a big string with protodef (is the length of your string
available somewhere ?) then use js split method

**Comment by louis030195** [comment]
Solved.
See [examples](https://github.com/AstrubTools/dofus-protocol/blob/master/src/utils/datatypes/dofus.js)
